// Mocks generated by Mockito 5.4.6 from annotations
// in mesa_auth_client/test/mesa_auth_client_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mesa_auth_client/src/api_client.dart' as _i3;
import 'package:mesa_auth_client/src/models/auth_tokens.dart' as _i2;
import 'package:mesa_auth_client/src/session_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthTokens_0 extends _i1.SmartFake implements _i2.AuthTokens {
  _FakeAuthTokens_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthTokens> login(
    String? id,
    String? password,
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [id, password, phone]),
            returnValue: _i4.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(
                this,
                Invocation.method(#login, [id, password, phone]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthTokens>);

  @override
  _i4.Future<_i2.AuthTokens> refresh(String? sessionId, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [sessionId, refreshToken]),
            returnValue: _i4.Future<_i2.AuthTokens>.value(
              _FakeAuthTokens_0(
                this,
                Invocation.method(#refresh, [sessionId, refreshToken]),
              ),
            ),
          )
          as _i4.Future<_i2.AuthTokens>);

  @override
  _i4.Future<void> logout(String? sessionId, String? refreshToken) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [sessionId, refreshToken]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SessionStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionStorage extends _i1.Mock implements _i5.SessionStorage {
  MockSessionStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveTokens(_i2.AuthTokens? tokens) =>
      (super.noSuchMethod(
            Invocation.method(#saveTokens, [tokens]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.AuthTokens?> loadTokens() =>
      (super.noSuchMethod(
            Invocation.method(#loadTokens, []),
            returnValue: _i4.Future<_i2.AuthTokens?>.value(),
          )
          as _i4.Future<_i2.AuthTokens?>);

  @override
  _i4.Future<void> clearTokens() =>
      (super.noSuchMethod(
            Invocation.method(#clearTokens, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
